In [2]:
import numpy as np
import pandas as pd

In [3]:
dict1 = {
  "name" : ['ravi' , "rohan" , "kajal" , "devesh"],"marks" : [99, 85, 100, 99], "city" : ["jaipur" , "delhi" , "jaipur" ,"panjab"]
  
}

In [6]:
df = pd.DataFrame(dict1)

In [7]:
df

     name  marks    city
0    ravi     99  jaipur
1   rohan     85   delhi
2   kajal    100  jaipur
3  devesh     99  panjab

In [8]:
df.to_csv('test.csv')

In [10]:
df.to_csv('test.csv', index = False)

In [12]:
df.head(2)

    name  marks    city
0   ravi     99  jaipur
1  rohan     85   delhi

In [13]:
df.tail(2)

     name  marks    city
2   kajal    100  jaipur
3  devesh     99  panjab

In [15]:
df.describe()

            marks
count    4.000000
mean    95.750000
std      7.182154
min     85.000000
25%     95.500000
50%     99.000000
75%     99.250000
max    100.000000

In [19]:
test = pd.read_csv('test.csv')

In [25]:
test['name']['2'] ='frind'

C:\Users\Ravi\AppData\Local\Temp\ipykernel_14276\2186252532.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['name']['2'] ='frind'